### ISSUE TITLE
Adding Travis-CI/CodeCov to repo

### ISSUE THREAD

**Issue by janash** [MolSSI-Education/python-package-best-practices#20]
In the past, and in the current episode, we add Travis-CI and CodeCov by going to the websites and authorizing the apps. An alternative would be to add these through [GitHub Marketplace](https://github.com/marketplace).

This would also connect to GitHub Actions (when we start using it for the workshop) which you can find through Marketplace.

Thoughts? (@JoaoRodrigues )

**Comment by JoaoRodrigues** [comment]
Hi @janash 

I just went over the process of setting up Travis through the Marketplace and it's much simpler than what I wrote yesterday. I would be happy to edit the CI episode!

**Comment by janash** [comment]
Edit it if you have time! I don't know that it's simpler, but it might be more uniform for future episodes (using GitHub Actions). 

There is also the caveat when going through the marketplace that you have to actively choose the free plans. At least for me, the Travis-CI it gives me through marketplace is default a plan that is $199 a month (I can switch it to Open Source/Free). I think it may not matter if you're on a trial - not sure how it would all work with billing...

**Comment by JoaoRodrigues** [comment]
Done, have a look! I also noticed that, so I wrote a couple of 'warnings' and will have people scroll down the page, instead of clicking on the 'Set up free trial' button.
