### ISSUE TITLE
WSL as the command prompt & environment of choice in Windows

### ISSUE THREAD

**Issue by radifar** [MolSSI-Education/python-package-best-practices#46]
In PR #45 WSL was mentioned, which reminds me that there are [many benefit](https://devblogs.microsoft.com/premier-developer/why-developers-should-install-wsl-today/) from using it. I think the greatest benefit is that we can make the working environment similar between Windows, Linux, and MacOS. WSL is also supported by VS Code and Pycharm.

So I propose using WSL for Windows users in this workshop. Hopefully, we can also use the command prompt directly inside IDE without any trouble. Which IMO very helpful for the student, rather than switching back and forth between VS Code and command prompt (or Powershell).

**Comment by janash** [comment]
I think it would be a nice optional thing to do. However, setting it up is a little heavy to only be used once in a workshop. If the students think they might use it again, it would be a good idea, but not otherwise. We could give it as an option and explain the benefits, but I don't want to make it a requirement.

**Comment by radifar** [comment]
> However, setting it up is a little heavy to only be used once in a workshop. 

Yes, I was thinking the same.

> If the students think they might use it again, it would be a good idea, but not otherwise. We could give it as an option and explain the benefits, but I don't want to make it a requirement.

After a little bit of research, I think you are right. There are actually very few of Windows specific step in the whole course, on the other hand setting up the WSL environment and integrating VS Code with WSL is too much of work for this course.

Thanks, I'll close this issue.
